---
- name: Prepare the disk(s)
  hosts: pc
  vars:
    partitions:
      - efi
      - swap
      - primary
    efi_end: 256MiB
    swap_start: "{{ efi_end }}"
    primary_partition_name: cryptroot
    btrfs_partition_temp_mount_path: /mnt
  tasks:
    - import_tasks: tasks/gather/device.yaml

    - import_tasks: tasks/gather/partition/is_encrypted.yaml
    - import_tasks: tasks/gather/partition/is_opened.yaml

    - import_tasks: tasks/cleanup/unmount.yaml
    - import_tasks: tasks/cleanup/disable_swap.yaml
    - import_tasks: tasks/cleanup/partition/close_encrypted.yaml
    - import_tasks: tasks/cleanup/partition/remove_all.yaml

    - import_tasks: tasks/partition/create_all.yaml
    - import_tasks: tasks/partition/format_all.yaml

    - import_tasks: tasks/partition/btrfs/create_subvolumes.yaml
    - import_tasks: tasks/partition/btrfs/mount_subvolumes.yaml
    - import_tasks: tasks/system/arch/bootstrap.yaml
    - import_tasks: tasks/partition/generate_fstab.yaml
