---
- name: Unmount mount points from possible previous runs
  ansible.posix.mount:
    path: "{{ system_mount_path }}{{ item }}"
    state: unmounted
  loop:
    - /home
    - /boot
    - "{{ system_mount_path }}"
    - /
