---
- import_tasks: tasks/partition/format_plain.yaml

- import_tasks: tasks/gather/partition/is_encrypted.yaml
- name: Encrypt the primary partition
  ansible.builtin.shell:
    cmd: cryptsetup luksFormat "{{ install_device }}{{ partitions | ansible.utils.index_of('eq', 'primary') + 1 }}"
    stdin: "{{ disk_encryption_passphrase }}\n{{ disk_encryption_passphrase }}"
  when:
    is_primary_encrypted.rc == 1
  tags:
    - encrypt

- import_tasks: tasks/gather/partition/is_opened.yaml
- import_tasks: tasks/partition/open_encrypted.yaml

- name: Format the primary partition
  community.general.filesystem:
    fstype: btrfs
    dev: /dev/mapper/{{ primary_partition_name }}
  tags:
    - format_after_encrypt
