---
- name: Format the efi partition
  ansible.builtin.shell:
    cmd: mkfs.fat -F32 "{{ install_device }}{{ partitions | ansible.utils.index_of('eq', 'efi') + 1 }}"
  tags:
    - format

- name: Format the swap partition
  community.general.filesystem:
    fstype: swap
    dev: "{{ install_device }}{{ partitions | ansible.utils.index_of('eq', 'swap') + 1 }}"
  tags:
    - format

- name: Enable swapping
  ansible.builtin.shell:
    cmd: swapon "{{ install_device }}{{ partitions | ansible.utils.index_of('eq', 'swap') + 1 }}"
  when: ansible_facts.swaptotal_mb == 0
  tags:
    - format
